export const SET_DRAWER = 'SET_DRAWER';

export const SERVER_CONNECTED = 'SERVER_CONNECTED';
export const UPDATE_FRONTEND = 'UPDATE_FRONTEND';
export const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED';
